# Importing basic libraries 

In [3]:
!pip install pandas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

You should consider upgrading via the 'C:\Users\gupta\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


     ---------------------------------------- 10.9/10.9 MB 7.8 MB/s eta 0:00:00
     -------------------------------------- 500.7/500.7 KB 6.3 MB/s eta 0:00:00


In [4]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(len(y))
count1 = 0
count2 = 0
for i in y:
    if i==1: count1+=1
    else: count2+=1
print(count1,count2, count1/count2)

1337
732 605 1.209917355371901


# Splitting the dataset

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

# Logistic regression
## Importing classifier

In [5]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [6]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 

## Testing the model

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[147   0]
 [  3 185]]


0.991044776119403

# Naive Bayes (Gaussian)
## Import Classifier

In [8]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [9]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1  1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [-1 -1]
 [-1  1]
 [ 1  1]
 [-1  1]
 [-1 -1]
 [-1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [-1 -1]
 [-1  1]
 [-1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 

## Testing the model

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[136  11]
 [ 58 130]]


0.7940298507462686

# SVM
## Importing Classifier

In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [12]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 

## Testing the classifier

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[147   0]
 [  4 184]]


0.9880597014925373

# KNN
## Importing classifier

In [14]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [15]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [-1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[138   9]
 [ 10 178]]


0.9432835820895522

# Random Forest
## Importing classifier

In [17]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [18]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1 -1]
 [-1 -1]
 [ 1  1]
 [-1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [ 1  1]
 [ 1  1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[141   6]
 [  2 186]]


0.9761194029850746