In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('og_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[39.03 38.66 39.03 ... 39.03 39.03 39.03]
 [39.41 39.41 39.41 ... 39.41 39.78 39.78]
 [39.78 39.78 39.78 ... 40.15 40.15 40.15]
 ...
 [72.63 72.89 72.63 ... 72.63 72.63 72.63]
 [72.63 72.63 72.63 ... 72.63 72.63 72.63]
 [72.63 72.63 72.63 ... 72.89 72.89 72.89]]


In [5]:
print(len(dataset))

4474


In [7]:
dataset = dataset.drop_duplicates()
print(len(dataset))

1337


In [8]:
dataset.to_csv('data.csv')